### ISSUE TITLE
refactor: implement the usage of The New CSS Reset

### ISSUE THREAD

**Issue by Geezgus** [oenzoferrari/missopad#6]
# RESET browsers' in-built CSS 💡 
Reset all browsers' in-built CSS would allow better consistency between browsers and give more freedom to style developers. A good option for such would be [The New CSS Reset](https://github.com/elad2412/the-new-css-reset), by [elad2412](https://github.com/elad2412), which is an easy-to-understand, life-saver single-sheet tool to have around on web projects. 

## How to 📖
Create a `reset.css`, then import [the-new-css-reset](https://github.com/elad2412/the-new-css-reset/blob/main/css/reset.css) (maintained by [elad2412](https://github.com/elad2412)) in the project.

**Comment by oenzoferrari** [comment]
Resolved in #7
